spring.application.name=ParkinsonTapWeb
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/parkinsontap
spring.datasource.url=jdbc:postgresql://localhost:5433/parkinsontap
spring.jpa.hibernate.ddl-auto=update

spring.datasource.username=user
spring.datasource.password=password

spring.datasource.tomcat.max-active=10
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

